# === НАСТРОЙКИ ДЛЯ БЭКЕНДА (ЭКСПЕРИМЕНТ) ===
# Этот раздел пытается указать Netlify, как "собрать" и "запустить" backend.

[build]
  # Указываем команду для установки зависимостей и потенциальной "сборки" бэкенда
  # (хотя стандартный Node.js сервер её не требует)
  command = "cd backend && npm install"
  
  # Указываем директорию, где будет находиться "результат сборки".
  # Для Node.js сервера это обычно корневая папка самого сервера.
  # Netlify ожидает здесь статические файлы, поэтому указываем папку бэкенда.
  # Это может не сработать, как ожидается.
  publish = "backend/"
  
  # Указываем, где находятся Serverless Functions (если бы они были).
  # Мы переопределяем стандартный путь netlify/functions.
  # functions = "backend/functions/" # Закомментировано, так как мы пытаемся запустить весь сервер

# === ПОПЫТКА УКАЗАТЬ ТОЧКУ ВХОДА ДЛЯ NODE.JS (ЭКСПЕРИМЕНТ) ===
# Netlify не имеет стандартной директивы для запуска Node.js сервера.
# Ниже директива НЕ является официальной поддержкой Netlify для запуска серверов.
# Это попытка "обмануть" систему, и она, скорее всего, НЕ сработает.
# [functions] # Используем секцию functions, так как других нет
#   # Нет стандартного способа указать "node server.js"
#   # Эта часть НЕ будет работать как ожидается для полноценного сервера.
#   # included_files = ["backend/**/*"] # Включить файлы бэкенда в функции (если бы они были функциями)

# === НАСТРОЙКИ ДЛЯ ФРОНТЕНДА (если он тоже в этом репо) ===
# Если вы хотите, чтобы Netlify также обслуживал фронтенд из той же деплойки
# (что не рекомендуется, лучше разделить), можно добавить:
#
# [[plugins]]
# package = "@netlify/plugin-nextjs" # Если бы фронтенд был Next.js
# # Или другие плагины для React/Vite, если они существуют для Netlify напрямую
#
# [build.frontend]
#   # Это гипотетическая секция, Netlify так не поддерживает
#   # command = "cd frontend && npm install && npm run build"
#   # publish = "frontend/dist"

# === ОБРАБОТКА МАРШРУТОВ (ДЛЯ КЛИЕНТСКОГО РОУТИНГА ИЛИ API) ===
# Если бы у нас были Serverless Functions или статика, это было бы нужно.
# Для запуска сервера это не применимо.

# Пример перенаправления для клиентского роутинга React (если бы фронтенд был собран)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# === ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ===
# Переменные окружения нужно устанавливать в интерфейсе Netlify:
# Site settings > Build & deploy > Environment

# === ВАЖНО ===
# Эта конфигурация экспериментальная.
# Netlify предназначен для статических сайтов и Serverless Functions.
# Запуск полноценного Node.js сервера с `app.listen()` здесь невозможен.
# === КОНЕЦ ВАЖНО ===
[dev]
  command = "node server.js"
